=== smartive/flutter-design-system-generator/design-system.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/smartive/flutter-design-system-generator/blob/main/design-system.schema.json",
  "title": "Design System Configuration",
  "description": "Configuration for the design_system_generator (build_runner).",
  "type": "object",
  "properties": {
    "colors": {
      "title": "Colors",
      "description": "The definition of a color (hex) or a color palette (map of colors).",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "oneOf": [
                {
                  "type": "string",
                  "pattern": "^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"
                },
                {
                  "$ref": "#/$defs/color"
                }
              ]
            }
          }
        },
        {
          "const": false
        }
      ]
    },
    "typography": {
      "title": "Typographies",
      "description": "Definition for text styles. Either a style directly or a map of styles. By default, text styles are not created.",
      "default": false,
      "oneOf": [
        {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^(?!family|size|weight|lineHeight|letterSpacing|wordSpacing)[a-zA-Z][a-zA-Z0-9]*$": {
              "oneOf": [
                {
                  "$ref": "#/$defs/textStyle"
                },
                {
                  "$ref": "#/$defs/typography"
                }
              ]
            }
          }
        },
        {
          "const": false
        }
      ]
    },
    "screens": {
      "title": "Screen Sizes",
      "description": "A definition of the screen sizes. This will create the breakpoints and the responsive helper.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "integer",
              "exclusiveMinimum": 0
            }
          }
        },
        {
          "const": false
        }
      ]
    },
    "spacings": {
      "title": "Spatial Values",
      "description": "A definition spatials (spacings).",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 0,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "integer",
              "multipleOf": 1
            }
          }
        },
        {
          "const": false
        }
      ]
    },
    "borderWidths": {
      "title": "Border width values",
      "description": "A map of border width values.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 0,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "integer",
              "multipleOf": 1
            }
          }
        }
      ]
    },
    "borderRadius": {
      "title": "Border Radii",
      "description": "A map of border radius values.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 0,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "integer",
              "minimum": 0
            }
          }
        },
        { "const": false }
      ]
    },
    "shadows": {
      "title": "Shadows",
      "description": "A map of box shadow definitions.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 0,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "$ref": "#/$defs/shadow"
            }
          }
        },
        {
          "const": false
        }
      ]
    }
  },
  "$defs": {
    "color": {
      "title": "Color",
      "description": "A definition of a color (hex) or a color palette (map of colors).",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "oneOf": [
            {
              "type": "string",
              "pattern": "^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"
            },
            {
              "$ref": "#/$defs/color"
            }
          ]
        }
      }
    },
    "textStyle": {
      "title": "Text Style",
      "description": "Effective text style definition.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "family": {
          "type": "string",
          "description": "The font family of the text style (e.g. Roboto)."
        },
        "weight": {
          "description": "The font weight of the text style (e.g. 100).",
          "enum": [100, 200, 300, 400, 500, 600, 700, 800, 900]
        },
        "size": {
          "description": "The font size of the text style (e.g. 16).",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "lineHeight": {
          "description": "The line height of the text style (e.g. 24).",
          "type": "number",
          "exclusiveMinimum": 0
        },
        "letterSpacing": {
          "description": "The letter spacing (or 'kerning') of the text style (e.g. 0.5). This value may also be negative.",
          "type": "number"
        },
        "wordSpacing": {
          "description": "The word spacing of the text style (e.g. 15). This value may also be negative.",
          "type": "number"
        }
      }
    },
    "typography": {
      "title": "Typography",
      "description": "A definition of a typography setting with font family and other settings OR a subobject.",
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^(?!family|size|weight|lineHeight|letterSpacing|wordSpacing)[a-zA-Z0-9]+$": {
          "oneOf": [
            {
              "$ref": "#/$defs/textStyle"
            },
            {
              "$ref": "#/$defs/typography"
            }
          ]
        }
      }
    },
    "shadow": {
      "title": "Shadow",
      "description": "A box shadow definition.",
      "type": "object",
      "required": ["blurRadius", "spreadRadius", "offset"],
      "additionalProperties": false,
      "properties": {
        "blurRadius": {
          "type": "number",
          "minimum": 0
        },
        "spreadRadius": {
          "type": "number"
        },
        "offset": {
          "type": "object",
          "required": ["dx", "dy"],
          "additionalProperties": false,
          "properties": {
            "dx": {
              "type": "number"
            },
            "dy": {
              "type": "number"
            }
          }
        }
      }
    },
    "iconSizes": {
      "title": "Icon sizes",
      "description": "A definition of the icon sizes in px.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 0,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "integer",
              "multipleOf": 1
            }
          }
        }
      ]
    }
  }
}

=== smartive/flutter-design-system-generator/example/design-system.json
{
  "$schema": "../design-system.schema.json",
  "colors": {
    "orange": {
      "DEFAULT": "#FFA500",
      "light": "#FFDAB9",
      "dark": "#FF8C00"
    },
    "white": "#FFFFFF",
    "black": "#000000",
    "halfTransparentBlue": "#0000FF80",
    "neutral": {
      "100": {
        "DEFAULT": "#F5F5F5",
        "light": "#FFFFFF"
      }
    }
  },
  "screens": {
    "medium": 700,
    "big": 1200
  },
  "spacings": {
    "small": 10,
    "medium": 20,
    "big": -30
  },
  "borderRadius": {
    "normal": 8,
    "full": 9999
  }
}
